# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae2a2ebd276e03b7843eaee03b032864b64287ae6469ca22cef4b27bc758be2b42d6eb6ee9becfb0f88a8dbac7a7d030614f2e2ad5574e896d73cb1f8ddd7a37

test:
  secret_key_base: 43126a44ef1c966dfb13ab0dadb85fe1578979f980dfbbffabc643fe4bf1d9c685956d1ddb1797377cb2115a2552dcc4496f0944e2d8ada447d44322866d7f14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
